import streamlit as st
import streamlit.components.v1 as components
import time, base64, hashlib, secrets
import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool
from pathlib import Path
from datetime import datetime, timedelta

ROOT=Path(__file__).resolve().parent
ETAPAS=["BASE","FOTO","DIMENSÕES","VÍDEO","CRIAR ANÚNCIO","PROMOÇÃO","ADS"]
PERFIS=["ADMINISTRADOR","GESTOR","FUNCIONÁRIO"]
PRIORIDADES=["NORMAL","PRIORIDADE","URGENTE"]
PESO_PRI={"URGENTE":0,"PRIORIDADE":1,"NORMAL":2}
CANAIS=[
    "MERCADO LIVRE — ABX","MERCADO LIVRE — RWX","MERCADO LIVRE — DANFERX",
    "SHOPEE — ABX","SHOPEE — RWX","SHOPEE — DANFERX","TIKTOK SHOP — ABX"
]

def _img_b64(path):
    with open(path,"rb") as f:return base64.b64encode(f.read()).decode()
logo_b64=_img_b64(ROOT/"logo_abxon.jpg")
st.set_page_config(page_title="Esteira ABX-ON",page_icon=str(ROOT/"favicon_abxon.png"),layout="wide")

@st.cache_resource(show_spinner=False)
def get_pool():
    url=st.secrets.get("DATABASE_URL","")
    if not url:
        raise RuntimeError("DATABASE_URL não configurada nos Secrets do Streamlit.")
    # Reaproveita conexões entre os reruns do Streamlit, evitando novo handshake
    # com o Supabase a cada clique.
    return ConnectionPool(
        conninfo=url,
        min_size=1,
        max_size=6,
        timeout=8,
        kwargs={"row_factory": dict_row},
        open=True,
    )

def con():
    return get_pool().connection()

def now(): return datetime.now().isoformat(timespec="seconds")
def sh(s): return hashlib.sha256(s.encode()).hexdigest()
def norm_login(s): return (s or "").strip().casefold()
def fmt(v):
    try:return datetime.fromisoformat(v).strftime("%d/%m/%Y %H:%M") if v else "—"
    except:return v or "—"
def fmt_data(v):
    if not v:return "—"
    try:
        if isinstance(v,str): return datetime.fromisoformat(v).strftime("%d/%m/%Y")
        return v.strftime("%d/%m/%Y")
    except:return str(v)
def age(v):
    if not v:return "—"
    try:m=max(0,int((datetime.now()-datetime.fromisoformat(v)).total_seconds()/60))
    except:return "—"
    if m<60:return f"{m} min"
    if m<1440:return f"{m//60}h {m%60:02d}min"
    return f"{m//1440}d {(m%1440)//60}h"

@st.cache_resource(show_spinner=False)
def init():
    """Migração automática V7.2 executada uma única vez por processo."""
    with con() as c:
        # tabelas-base
        c.execute("""CREATE TABLE IF NOT EXISTS produtos(
            sku TEXT PRIMARY KEY,altura DOUBLE PRECISION,largura DOUBLE PRECISION,
            comprimento DOUBLE PRECISION,peso DOUBLE PRECISION,criado_em TEXT,
            foto_padrao TEXT,video_padrao TEXT,promo_padrao TEXT,ads_padrao TEXT)""")
        c.execute("""CREATE TABLE IF NOT EXISTS anuncios(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,sku TEXT,numero INTEGER,
            titulo TEXT,descricao TEXT,preco DOUBLE PRECISION,etapa TEXT DEFAULT 'BASE',
            status TEXT DEFAULT 'AGUARDANDO',link_foto TEXT,link_video TEXT,criado_em TEXT,
            atualizado_em TEXT,foto_override TEXT,video_override TEXT,promo_override TEXT,
            ads_override TEXT,responsavel TEXT,entrada_etapa_em TEXT,inicio_etapa_em TEXT,
            prioridade TEXT DEFAULT 'NORMAL',prazo TEXT,correcao_origem TEXT,
            correcao_destino TEXT,correcao_retorno TEXT,correcao_motivo TEXT)""")
        c.execute("""CREATE TABLE IF NOT EXISTS historico(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,anuncio_id BIGINT NOT NULL,
            data_hora TEXT,etapa TEXT,acao TEXT,observacao TEXT)""")
        c.execute("""CREATE TABLE IF NOT EXISTS usuarios(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,nome TEXT NOT NULL,
            login TEXT UNIQUE NOT NULL,senha TEXT NOT NULL,perfil TEXT NOT NULL DEFAULT 'FUNCIONÁRIO',
            ativo INTEGER NOT NULL DEFAULT 1,criado_em TEXT NOT NULL)""")
        c.execute("""CREATE TABLE IF NOT EXISTS usuario_etapas(
            usuario_id BIGINT NOT NULL,etapa TEXT NOT NULL,UNIQUE(usuario_id,etapa))""")
        c.execute("""CREATE TABLE IF NOT EXISTS login_sessions(
            token TEXT PRIMARY KEY,usuario_id BIGINT NOT NULL,expira_em TEXT NOT NULL)""")

        # V7: conteúdo compartilhado no SKU
        c.execute("ALTER TABLE produtos ADD COLUMN IF NOT EXISTS descricao TEXT")
        # V7: cada canal/plataforma é um trabalho de anúncio
        c.execute("ALTER TABLE anuncios ADD COLUMN IF NOT EXISTS canal TEXT")
        c.execute("ALTER TABLE anuncios ADD COLUMN IF NOT EXISTS preco_premium DOUBLE PRECISION")
        c.execute("ALTER TABLE anuncios ADD COLUMN IF NOT EXISTS preco_classico DOUBLE PRECISION")
        c.execute("ALTER TABLE anuncios ADD COLUMN IF NOT EXISTS preco_shopee DOUBLE PRECISION")
        c.execute("ALTER TABLE anuncios ADD COLUMN IF NOT EXISTS preco_tiktok DOUBLE PRECISION")
        c.execute("ALTER TABLE anuncios ADD COLUMN IF NOT EXISTS link_anuncio TEXT")
        c.execute("""CREATE TABLE IF NOT EXISTS anuncio_titulos(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            anuncio_id BIGINT NOT NULL REFERENCES anuncios(id) ON DELETE CASCADE,
            ordem INTEGER NOT NULL,titulo TEXT NOT NULL,UNIQUE(anuncio_id,ordem))""")
        c.execute("CREATE INDEX IF NOT EXISTS idx_anuncios_canal ON anuncios(canal)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_titulos_anuncio ON anuncio_titulos(anuncio_id)")

        # migração dos nomes antigos
        c.execute("UPDATE anuncios SET etapa='DIMENSÕES' WHERE etapa='FÍSICA'")
        c.execute("UPDATE anuncios SET etapa='PROMOÇÃO' WHERE etapa='PROMO'")
        c.execute("UPDATE usuario_etapas SET etapa='DIMENSÕES' WHERE etapa='FÍSICA'")
        c.execute("UPDATE usuario_etapas SET etapa='PROMOÇÃO' WHERE etapa='PROMO'")
        c.execute("UPDATE anuncios SET canal='LEGADO' WHERE canal IS NULL OR canal=''")
        # preserva título/descrição/preço legados
        c.execute("""INSERT INTO anuncio_titulos(anuncio_id,ordem,titulo)
                     SELECT id,1,titulo FROM anuncios a
                     WHERE COALESCE(titulo,'')<>'' AND NOT EXISTS
                     (SELECT 1 FROM anuncio_titulos t WHERE t.anuncio_id=a.id)""")
        c.execute("""UPDATE produtos p SET descricao=a.descricao FROM anuncios a
                     WHERE a.sku=p.sku AND COALESCE(p.descricao,'')='' AND COALESCE(a.descricao,'')<>''""")
        c.execute("""UPDATE anuncios SET preco_classico=preco
                     WHERE preco_classico IS NULL AND preco IS NOT NULL""")

        n=c.execute("SELECT COUNT(*) n FROM usuarios WHERE perfil='ADMINISTRADOR'").fetchone()["n"]
        if n==0:
            c.execute("""INSERT INTO usuarios(nome,login,senha,perfil,ativo,criado_em)
                         VALUES(%s,%s,%s,'ADMINISTRADOR',1,%s)""",
                      ("Administrador ABX-ON","admin",sh("abxon123"),now()))

def log(c,i,e,a,o=""):
    c.execute("INSERT INTO historico(anuncio_id,data_hora,etapa,acao,observacao) VALUES(%s,%s,%s,%s,%s)",(i,now(),e,a,o))

@st.cache_data(ttl=20, show_spinner=False)
def perms(uid):
    with con() as c:
        return [r["etapa"] for r in c.execute(
            "SELECT etapa FROM usuario_etapas WHERE usuario_id=%s",(uid,)
        )]

def criar_user(nome,login,senha,perfil,ets):
    login=norm_login(login)
    with con() as c:
        if c.execute("SELECT 1 FROM usuarios WHERE lower(login)=lower(%s)",(login,)).fetchone():
            raise psycopg.errors.UniqueViolation("Login já existe")
        uid=c.execute("""INSERT INTO usuarios(nome,login,senha,perfil,ativo,criado_em)
                         VALUES(%s,%s,%s,%s,1,%s) RETURNING id""",
                      (nome,login,sh(senha),perfil,now())).fetchone()["id"]
        for e in ets:c.execute("INSERT INTO usuario_etapas(usuario_id,etapa) VALUES(%s,%s) ON CONFLICT DO NOTHING",(uid,e))
    perms.clear()

def update_user(uid,nome,perfil,ativo,ets,senha=""):
    with con() as c:
        c.execute("UPDATE usuarios SET nome=%s,perfil=%s,ativo=%s WHERE id=%s",(nome,perfil,int(ativo),uid))
        if senha:c.execute("UPDATE usuarios SET senha=%s WHERE id=%s",(sh(senha),uid))
        c.execute("DELETE FROM usuario_etapas WHERE usuario_id=%s",(uid,))
        for e in ets:c.execute("INSERT INTO usuario_etapas(usuario_id,etapa) VALUES(%s,%s) ON CONFLICT DO NOTHING",(uid,e))
    perms.clear()

def titulos_anuncio(c,aid):
    return [r["titulo"] for r in c.execute("SELECT titulo FROM anuncio_titulos WHERE anuncio_id=%s ORDER BY ordem",(aid,)).fetchall()]

def resumo_anuncio(a,p,titulos):
    st.markdown(f"**Canal:** {a['canal'] or '—'}")
    st.markdown("**Título(s):**")
    for i,t in enumerate(titulos,1):
        st.write(f"{i}. {t}")
        st.caption(f"{len(t)} caracteres")
    desc=(p["descricao"] if p else "") or a.get("descricao") or ""
    st.markdown(f"**Descrição:** {len(desc)} caracteres")
    st.text_area("Descrição cadastrada",desc,height=120,disabled=True,key=f"resdesc_{a['id']}_{a['etapa']}")
    canal=(a["canal"] or "")
    if canal.startswith("MERCADO LIVRE"):
        c1,c2=st.columns(2)
        c1.metric("Preço Premium",f"R$ {float(a['preco_premium'] or 0):,.2f}".replace(",", "X").replace(".",",").replace("X","."))
        c2.metric("Preço Clássico",f"R$ {float(a['preco_classico'] or 0):,.2f}".replace(",", "X").replace(".",",").replace("X","."))
    elif canal.startswith("SHOPEE"):
        st.metric("Preço Shopee",f"R$ {float(a['preco_shopee'] or 0):,.2f}".replace(",", "X").replace(".",",").replace("X","."))
    elif canal.startswith("TIKTOK"):
        st.metric("Preço TikTok Shop",f"R$ {float(a['preco_tiktok'] or 0):,.2f}".replace(",", "X").replace(".",",").replace("X","."))
    st.caption(f"Prioridade: {a['prioridade']} · Prazo: {fmt_data(a['prazo'])}")

def criar_produto(sku,canais,q_ml,titulos_ml,titulo_shopee,titulo_tiktok,descricao,
                  preco_premium,preco_classico,preco_shopee,preco_tiktok,user,prioridade,prazo):
    with con() as c:
        t=now()
        c.execute("""INSERT INTO produtos(sku,criado_em,descricao) VALUES(%s,%s,%s)
                     ON CONFLICT (sku) DO UPDATE SET descricao=EXCLUDED.descricao""",(sku,t,descricao))
        n=c.execute("SELECT COALESCE(MAX(numero),0)n FROM anuncios WHERE sku=%s",(sku,)).fetchone()["n"]
        for idx,canal in enumerate(canais,1):
            if canal.startswith("MERCADO LIVRE"):
                tits=titulos_ml
                pp,pc=preco_premium,preco_classico
            elif canal.startswith("SHOPEE"):
                tits=[titulo_shopee]
                pp=pc=None
            else:
                tits=[titulo_tiktok]
                pp=pc=None
            ps=preco_shopee if canal.startswith("SHOPEE") else None
            pt=preco_tiktok if canal.startswith("TIKTOK") else None
            aid=c.execute("""INSERT INTO anuncios(
                sku,numero,titulo,descricao,preco,preco_premium,preco_classico,preco_shopee,preco_tiktok,canal,
                etapa,status,criado_em,atualizado_em,entrada_etapa_em,prioridade,prazo)
                VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,'BASE','AGUARDANDO',%s,%s,%s,%s,%s)
                RETURNING id""",
                (sku,n+idx,tits[0],descricao,pc,pp,pc,ps,pt,canal,t,t,t,prioridade,prazo)).fetchone()["id"]
            for ordem,titulo in enumerate(tits,1):
                c.execute("INSERT INTO anuncio_titulos(anuncio_id,ordem,titulo) VALUES(%s,%s,%s)",(aid,ordem,titulo))
            log(c,aid,"BASE","ANÚNCIO CRIADO",f"{user['nome']} | {canal}")

def abrir(i,user):
    with con() as c:
        a=c.execute("SELECT * FROM anuncios WHERE id=%s",(i,)).fetchone()
        if not a["inicio_etapa_em"]:
            t=now(); corr=bool(a["correcao_retorno"] or a["correcao_origem"] or a["correcao_destino"])
            c.execute("""UPDATE anuncios SET inicio_etapa_em=%s,responsavel=%s,status=%s,atualizado_em=%s WHERE id=%s""",
                      (t,user["nome"],"CORRIGIR" if corr else "EM ANDAMENTO",t,i))
            log(c,i,a["etapa"],"CORREÇÃO ABERTA" if corr else "TRABALHO ABERTO",user["nome"])

def finalizar(i,user,campos):
    with con() as c:
        a=c.execute("SELECT * FROM anuncios WHERE id=%s",(i,)).fetchone()
        p=c.execute("SELECT * FROM produtos WHERE sku=%s",(a["sku"],)).fetchone()
        etapa=a["etapa"]
        if etapa=="DIMENSÕES":
            if any(float(campos.get(k,0) or 0)<=0 for k in ["altura","largura","comprimento","peso"]):
                return "Preencha altura, largura, comprimento e peso."
            c.execute("UPDATE produtos SET altura=%s,largura=%s,comprimento=%s,peso=%s WHERE sku=%s",
                      (campos["altura"],campos["largura"],campos["comprimento"],campos["peso"],a["sku"]))
        elif etapa=="VÍDEO":
            if not campos.get("video","").strip(): return "Informe o link do vídeo."
            c.execute("UPDATE produtos SET video_padrao=%s WHERE sku=%s",(campos["video"].strip(),a["sku"]))
            c.execute("UPDATE anuncios SET link_video=%s WHERE id=%s",(campos["video"].strip(),i))
        elif etapa=="CRIAR ANÚNCIO":
            c.execute("UPDATE anuncios SET link_anuncio=%s WHERE id=%s",(campos.get("link_anuncio","").strip() or None,i))

        t=now(); log(c,i,etapa,"ETAPA CONCLUÍDA",user["nome"])
        retorno=a["correcao_retorno"] or a["correcao_origem"]
        corr=bool(a["correcao_retorno"] or a["correcao_origem"] or a["correcao_destino"])
        if corr and retorno:
            c.execute("""UPDATE anuncios SET etapa=%s,status='AGUARDANDO',responsavel=NULL,entrada_etapa_em=%s,
                inicio_etapa_em=NULL,atualizado_em=%s,correcao_origem=NULL,correcao_destino=NULL,
                correcao_retorno=NULL,correcao_motivo=NULL WHERE id=%s""",(retorno,t,t,i))
            log(c,i,retorno,"CORREÇÃO CONCLUÍDA / RETORNO DIRETO",user["nome"])
            return None
        k=ETAPAS.index(etapa)
        if k==len(ETAPAS)-1:
            c.execute("UPDATE anuncios SET status='OK',responsavel=%s,atualizado_em=%s WHERE id=%s",(user["nome"],t,i))
            log(c,i,"ADS","ANÚNCIO FINALIZADO",user["nome"])
        else:
            prox=ETAPAS[k+1]
            c.execute("""UPDATE anuncios SET etapa=%s,status='AGUARDANDO',responsavel=NULL,
                entrada_etapa_em=%s,inicio_etapa_em=NULL,atualizado_em=%s WHERE id=%s""",(prox,t,t,i))
            log(c,i,prox,"TRABALHO RECEBIDO",a["canal"] or "")
    return None

def enviar_correcao(i,user,destino,motivo):
    with con() as c:
        a=c.execute("SELECT * FROM anuncios WHERE id=%s",(i,)).fetchone();t=now()
        c.execute("""UPDATE anuncios SET etapa=%s,status='CORRIGIR',responsavel=NULL,entrada_etapa_em=%s,
            inicio_etapa_em=NULL,atualizado_em=%s,correcao_origem=%s,correcao_destino=%s,
            correcao_retorno=%s,correcao_motivo=%s WHERE id=%s""",
            (destino,t,t,a["etapa"],destino,a["etapa"],motivo,i))
        log(c,i,destino,"CORREÇÃO SOLICITADA",f"{user['nome']} | origem {a['etapa']} | {motivo}")

def fila(etapa):
    with con() as c: rows=c.execute("SELECT * FROM anuncios WHERE etapa=%s AND status!='OK'",(etapa,)).fetchall()
    return sorted(rows,key=lambda x:(0 if x["status"]=="CORRIGIR" else 1,PESO_PRI.get(x["prioridade"],2),x["entrada_etapa_em"] or ""))

def trabalho(a,user):
    aid=a["id"]
    with con() as c:
        a=c.execute("SELECT * FROM anuncios WHERE id=%s",(aid,)).fetchone()
        if not a["inicio_etapa_em"]:
            t=now(); corr=bool(a["correcao_retorno"] or a["correcao_origem"] or a["correcao_destino"])
            c.execute("""UPDATE anuncios SET inicio_etapa_em=%s,responsavel=%s,status=%s,atualizado_em=%s WHERE id=%s""",
                      (t,user["nome"],"CORRIGIR" if corr else "EM ANDAMENTO",t,aid))
            log(c,aid,a["etapa"],"CORREÇÃO ABERTA" if corr else "TRABALHO ABERTO",user["nome"])
            a=c.execute("SELECT * FROM anuncios WHERE id=%s",(aid,)).fetchone()
        p=c.execute("SELECT * FROM produtos WHERE sku=%s",(a["sku"],)).fetchone()
        tits=titulos_anuncio(c,aid)
    etapa=a["etapa"]
    ico="🔴 " if a["prioridade"]=="URGENTE" else "🟡 " if a["prioridade"]=="PRIORIDADE" else ""
    st.header(f"{ico}{a['sku']} · {a['canal'] or '—'}")
    st.caption(f"{etapa} · {a['responsavel'] or user['nome']} · em trabalho {age(a['inicio_etapa_em'])}")
    with st.expander("📋 Dados do anúncio",expanded=True):
        resumo_anuncio(a,p,tits)
        if p and all(p.get(k) for k in ["altura","largura","comprimento","peso"]):
            st.write(f"**Dimensões:** {p['altura']} × {p['largura']} × {p['comprimento']} · Peso {p['peso']}")
        if p and p.get("video_padrao"): st.write(f"**Vídeo:** {p['video_padrao']}")
        if a.get("link_anuncio"): st.write(f"**Link do anúncio:** {a['link_anuncio']}")

    corr=bool(a["correcao_retorno"] or a["correcao_origem"] or a["correcao_destino"])
    if corr:
        st.error(f"🔴 CORREÇÃO SOLICITADA POR {a['correcao_origem'] or 'ETAPA ANTERIOR'}")
        st.write(f"**Motivo:** {a['correcao_motivo'] or 'Sem observação'}")

    campos={}
    if etapa=="BASE":
        st.info("Responsável pela BASE: confira e ajuste título e descrição antes de encaminhar para FOTO.")
        with st.form(f"editar_base_{aid}"):
            novos_titulos=[]
            for idx,tit in enumerate(tits,1):
                nt=st.text_input(f"Título {idx}",value=tit,key=f"base_t_{aid}_{idx}")
                st.caption(f"{len(nt)} caracteres")
                novos_titulos.append(nt)
            nova_desc=st.text_area("Descrição",value=(p["descricao"] or ""),height=220,key=f"base_desc_{aid}")
            st.caption(f"{len(nova_desc)} caracteres")
            salvar_base=st.form_submit_button("💾 SALVAR ALTERAÇÕES DA BASE",use_container_width=True)
        if salvar_base:
            if any(not x.strip() for x in novos_titulos):
                st.error("Preencha todos os títulos.")
            elif not nova_desc.strip():
                st.error("Preencha a descrição.")
            else:
                with con() as c:
                    c.execute("UPDATE produtos SET descricao=%s WHERE sku=%s",(nova_desc.strip(),a["sku"]))
                    c.execute("UPDATE anuncios SET descricao=%s,atualizado_em=%s WHERE sku=%s",(nova_desc.strip(),now(),a["sku"]))
                    c.execute("DELETE FROM anuncio_titulos WHERE anuncio_id=%s",(aid,))
                    for ordem,tit in enumerate(novos_titulos,1):
                        c.execute("INSERT INTO anuncio_titulos(anuncio_id,ordem,titulo) VALUES(%s,%s,%s)",(aid,ordem,tit.strip()))
                    c.execute("UPDATE anuncios SET titulo=%s,atualizado_em=%s WHERE id=%s",(novos_titulos[0].strip(),now(),aid))
                    log(c,aid,"BASE","DADOS EDITADOS",user["nome"])
                st.success("Título(s) e descrição atualizados.")
                st.rerun()
    elif etapa=="FOTO":
        st.info("📷 Faça/prepare as fotos do produto. **Não é necessário inserir link de foto.**")
    elif etapa=="DIMENSÕES":
        campos["altura"]=st.number_input("Altura",0.0,value=float(p["altura"] or 0))
        campos["largura"]=st.number_input("Largura",0.0,value=float(p["largura"] or 0))
        campos["comprimento"]=st.number_input("Comprimento",0.0,value=float(p["comprimento"] or 0))
        campos["peso"]=st.number_input("Peso",0.0,value=float(p["peso"] or 0))
    elif etapa=="VÍDEO":
        campos["video"]=st.text_input("Link do vídeo",p["video_padrao"] or a["link_video"] or "")
    elif etapa=="CRIAR ANÚNCIO":
        st.success(f"🌐 Criar/publicar este anúncio em **{a['canal']}**.")
        campos["link_anuncio"]=st.text_input("Link do anúncio publicado (opcional)",a["link_anuncio"] or "")
    elif etapa=="PROMOÇÃO":
        st.info(f"🏷️ Configure a promoção na plataforma **{a['canal']}** e confirme quando concluir.")
    elif etapa=="ADS":
        st.info(f"📈 Configure/acompanhe o ADS de **{a['canal']}** e finalize.")

    label="✅ FINALIZAR CORREÇÃO" if corr else f"✅ FINALIZAR {etapa}"
    if st.button(label,type="primary",use_container_width=True):
        er=finalizar(a["id"],user,campos)
        if er:st.error(er)
        else:st.session_state.pop("aberto",None);st.rerun()

    destinos=[e for e in ETAPAS if ETAPAS.index(e)<ETAPAS.index(etapa)]
    if destinos and not corr:
        with st.expander("↩ Enviar para correção"):
            destino=st.selectbox("Enviar para qual etapa?",destinos)
            motivo=st.text_area("Motivo / observação")
            if st.button("ENVIAR CORREÇÃO"):
                if not motivo.strip():st.error("Informe o motivo.")
                else:enviar_correcao(a["id"],user,destino,motivo);st.session_state.pop("aberto",None);st.rerun()

def criar_sessao_persistente(uid):
    token=secrets.token_urlsafe(32); exp=(datetime.now()+timedelta(days=30)).isoformat(timespec="seconds")
    with con() as c:
        c.execute("DELETE FROM login_sessions WHERE usuario_id=%s OR expira_em<%s",(uid,now()))
        c.execute("INSERT INTO login_sessions(token,usuario_id,expira_em) VALUES(%s,%s,%s)",(token,uid,exp))
    return token
def usuario_por_token(token):
    if not token:return None
    with con() as c:return c.execute("""SELECT u.* FROM login_sessions s JOIN usuarios u ON u.id=s.usuario_id
        WHERE s.token=%s AND s.expira_em>%s AND u.ativo=1""",(token,now())).fetchone()
def remover_sessao(token):
    if token:
        with con() as c:c.execute("DELETE FROM login_sessions WHERE token=%s",(token,))

try:init()
except Exception as e:
    st.error("Não foi possível conectar/atualizar o banco PostgreSQL/Supabase.");st.code(str(e));st.stop()

COOKIE_NAME="abxon_login"
def set_cookie(name,value,days=30):
    components.html(f"""<script>document.cookie={name!r}+'='+{value!r}+'; max-age='+({days}*86400)+'; path=/; SameSite=Lax';</script>""",height=0)
def del_cookie(name):
    components.html(f"""<script>document.cookie={name!r}+'=; max-age=0; path=/; SameSite=Lax';</script>""",height=0)

if "uid" not in st.session_state:
    tok=st.context.cookies.get(COOKIE_NAME); u=usuario_por_token(tok)
    if u:st.session_state.uid=u["id"];st.session_state.login_token=tok

if "uid" not in st.session_state:
    st.markdown(f"""<div style="display:flex;align-items:center;gap:16px;margin:4px 0 8px 0;">
    <img src="data:image/jpeg;base64,{logo_b64}" style="height:58px;width:auto;object-fit:contain;">
    <div style="font-size:2.45rem;font-weight:800;">ESTEIRA ABX-ON</div></div>""",unsafe_allow_html=True)
    st.caption("Acesso interno")
    with st.form("login"):
        login=st.text_input("Usuário");senha=st.text_input("Senha",type="password")
        go=st.form_submit_button("ENTRAR",type="primary",use_container_width=True)
    if go:
        with con() as c:u=c.execute("SELECT * FROM usuarios WHERE lower(login)=lower(%s) AND senha=%s AND ativo=1",(norm_login(login),sh(senha))).fetchone()
        if u:
            tok=criar_sessao_persistente(u["id"]);set_cookie(COOKIE_NAME,tok,30)
            st.session_state.uid=u["id"];st.session_state.login_token=tok;time.sleep(.2);st.rerun()
        else:st.error("Usuário ou senha inválidos.")
    st.info("Utilize o usuário e a senha fornecidos pelo seu gestor ou responsável.")
    st.stop()

with con() as c:user=c.execute("SELECT * FROM usuarios WHERE id=%s",(st.session_state.uid,)).fetchone()
if not user or not user["ativo"]:st.session_state.clear();st.rerun()
ets=perms(user["id"]);adm=user["perfil"]=="ADMINISTRADOR";gest=user["perfil"] in ["ADMINISTRADOR","GESTOR"]
st.sidebar.write(f"**{user['nome']}**");st.sidebar.caption(user["perfil"])
if st.sidebar.button("Sair"):
    remover_sessao(st.session_state.get("login_token") or st.context.cookies.get(COOKIE_NAME))
    del_cookie(COOKIE_NAME);st.session_state.clear();time.sleep(.2);st.rerun()
menu=["🏠 Meus Trabalhos","🔎 Buscar"]+(["📊 Gestão"] if gest else [])+(["⚙️ Administração","➕ Novo Produto"] if adm else [])
pag=st.sidebar.radio("Menu",menu)

if pag=="🏠 Meus Trabalhos":
    minhas=ETAPAS if adm else [e for e in ets if e in ETAPAS]
    if not minhas:st.warning("O administrador ainda não atribuiu uma etapa ao seu acesso.");st.stop()
    if "aberto" in st.session_state:
        if st.button("← Voltar"):st.session_state.pop("aberto");st.rerun()
        trabalho({"id":st.session_state.aberto},user)
    else:
        st.header(f"Olá, {user['nome']} 👋")
        etapa=st.selectbox("Etapa",minhas) if len(minhas)>1 else minhas[0]
        rows=fila(etapa); hoje=datetime.now().strftime("%Y-%m-%d")
        with con() as c:feitos=c.execute("""SELECT COUNT(*) n FROM historico WHERE acao='ETAPA CONCLUÍDA'
            AND observacao=%s AND substr(data_hora,1,10)=%s""",(user["nome"],hoje)).fetchone()["n"]
        c1,c2,c3=st.columns(3);c1.metric("Para fazer",len(rows));c2.metric("Correções",sum(x["status"]=="CORRIGIR" for x in rows));c3.metric("Concluídos hoje",feitos)
        if rows and st.button("▶ ABRIR PRÓXIMO TRABALHO",type="primary",use_container_width=True):
            st.session_state.aberto=rows[0]["id"];st.rerun()
        for x in rows:
            ico="🔴" if x["prioridade"]=="URGENTE" else "🟡" if x["prioridade"]=="PRIORIDADE" else "⚪"
            with st.container(border=True):
                st.write(f"**{ico} {x['sku']} · {x['canal'] or '—'}**")
                st.caption(x["titulo"] or "Sem título")
                if x["status"]=="CORRIGIR":st.error(f"Correção: {x['correcao_motivo'] or 'Sem observação'}")
                else:st.caption(f"Na etapa há {age(x['entrada_etapa_em'])}")
                if st.button("ABRIR",key=f"a{x['id']}"):st.session_state.aberto=x["id"];st.rerun()

elif pag=="📊 Gestão":
    st.header("📊 Gestão ABX-ON")
    busca=st.text_input("🔎 Buscar SKU na Gestão").strip().upper()
    with con() as c:
        ativos=c.execute("SELECT * FROM anuncios WHERE status!='OK'").fetchall()
        hoje=datetime.now().strftime("%Y-%m-%d")
        entraram=c.execute("SELECT COUNT(*) n FROM anuncios WHERE substr(criado_em,1,10)=%s",(hoje,)).fetchone()["n"]
        finais=c.execute("SELECT COUNT(*) n FROM historico WHERE acao='ANÚNCIO FINALIZADO' AND substr(data_hora,1,10)=%s",(hoje,)).fetchone()["n"]
        corrs=c.execute("SELECT COUNT(*) n FROM anuncios WHERE status='CORRIGIR'").fetchone()["n"]
    a,b,c=st.columns(3);a.metric("Entraram hoje",entraram);b.metric("Finalizados hoje",finais);c.metric("Em correção",corrs)
    cols=st.columns(len(ETAPAS))
    for col,e in zip(cols,ETAPAS):col.metric(e,sum(x["etapa"]==e for x in ativos))
    if busca:
        with con() as c:
            ans=c.execute("SELECT * FROM anuncios WHERE sku=%s ORDER BY numero",(busca,)).fetchall()
            p=c.execute("SELECT * FROM produtos WHERE sku=%s",(busca,)).fetchone()
            hist=c.execute("""SELECT h.data_hora,a.canal,h.etapa,h.acao,h.observacao FROM historico h
                JOIN anuncios a ON a.id=h.anuncio_id WHERE a.sku=%s ORDER BY h.id DESC""",(busca,)).fetchall()
        if not ans:st.warning("SKU não encontrado.")
        for x in ans:
            with st.expander(f"{x['canal']} · {x['etapa']} / {x['status']}",expanded=True):
                with con() as c:tits=titulos_anuncio(c,x["id"])
                resumo_anuncio(x,p,tits)
                st.write(f"**Responsável:** {x['responsavel'] or '—'} · **Entrada:** {fmt(x['entrada_etapa_em'])}")
                if x.get("link_anuncio"):st.write(f"**Link publicado:** {x['link_anuncio']}")
                if adm:
                    st.divider()
                    confirmar=st.checkbox("Confirmo que desejo excluir este anúncio",key=f"conf_del_{x['id']}")
                    if st.button("🗑️ EXCLUIR ANÚNCIO",key=f"del_{x['id']}",type="secondary",disabled=not confirmar):
                        with con() as c:
                            c.execute("DELETE FROM historico WHERE anuncio_id=%s",(x["id"],))
                            c.execute("DELETE FROM anuncio_titulos WHERE anuncio_id=%s",(x["id"],))
                            c.execute("DELETE FROM anuncios WHERE id=%s",(x["id"],))
                        st.success("Anúncio excluído pela administração.")
                        st.rerun()
        if hist:
            st.subheader("🕘 Histórico completo do SKU")
            st.dataframe([dict(x) for x in hist],use_container_width=True,hide_index=True)
    else:
        st.subheader("Abrir uma etapa")
        e=st.selectbox("Etapa para inspecionar",ETAPAS)
        for x in fila(e):
            st.write(f"{x['prioridade']} · {x['sku']} · {x['canal']} · {x['status']} · parado {age(x['entrada_etapa_em'])} · {x['responsavel'] or 'aguardando'}")

elif pag=="⚙️ Administração":
    st.header("⚙️ Administração")
    t1,t2=st.tabs(["👥 Equipe e Acessos","📜 Histórico Geral"])
    with t1:
        with st.form("novo"):
            nome=st.text_input("Nome");login=st.text_input("Login");senha=st.text_input("Senha inicial",type="password")
            perfil=st.selectbox("Perfil",PERFIS,index=2);pe=st.multiselect("Etapas",ETAPAS)
            ok=st.form_submit_button("CRIAR ACESSO",type="primary")
        if ok:
            try:
                if nome and login and senha:criar_user(nome,login,senha,perfil,pe);st.success("Criado.");st.rerun()
                else:st.error("Preencha nome, login e senha.")
            except psycopg.errors.UniqueViolation:st.error("Login já existe.")
        with con() as c:us=c.execute("SELECT * FROM usuarios ORDER BY ativo DESC,nome").fetchall()
        for u in us:
            with st.expander(f"{'🟢' if u['ativo'] else '⚫'} {u['nome']} · {u['perfil']}"):
                n=st.text_input("Nome",u["nome"],key=f"n{u['id']}")
                pf=st.selectbox("Perfil",PERFIS,index=PERFIS.index(u["perfil"]),key=f"pf{u['id']}")
                at=st.checkbox("Ativo",bool(u["ativo"]),key=f"at{u['id']}")
                ee=st.multiselect("Etapas",ETAPAS,default=[x for x in perms(u["id"]) if x in ETAPAS],key=f"e{u['id']}")
                ns=st.text_input("Nova senha",type="password",key=f"s{u['id']}")
                if st.button("SALVAR",key=f"sv{u['id']}"):update_user(u["id"],n,pf,at,ee,ns);st.rerun()
    with t2:
        with con() as c:h=c.execute("""SELECT h.data_hora,a.sku,a.canal,h.etapa,h.acao,h.observacao
            FROM historico h JOIN anuncios a ON a.id=h.anuncio_id ORDER BY h.id DESC LIMIT 2000""").fetchall()
        st.dataframe([dict(x) for x in h],use_container_width=True,hide_index=True)

elif pag=="➕ Novo Produto":
    st.header("➕ Novo Produto / Anúncios")
    sku=st.text_input("SKU").strip().upper()
    canais=st.multiselect("Canais de publicação",CANAIS,help="Selecione todas as lojas/plataformas onde este SKU terá anúncio.")
    prioridade=st.selectbox("Prioridade",PRIORIDADES,index=0)
    prazo=st.date_input("Prazo",value=None,format="DD/MM/YYYY")

    tem_ml=any(x.startswith("MERCADO LIVRE") for x in canais)
    tem_shopee=any(x.startswith("SHOPEE") for x in canais)
    tem_tiktok=any(x.startswith("TIKTOK") for x in canais)

    st.subheader("Conteúdo do anúncio")
    titulos_ml=[]; titulo_shopee=""; titulo_tiktok=""
    if tem_ml:
        q_ml=int(st.number_input("Quantos títulos para o Mercado Livre?",1,20,3))
        for j in range(q_ml):
            v=st.text_input(f"Título Mercado Livre {j+1}",key=f"tml{j}")
            st.caption(f"{len(v)} caracteres")
            titulos_ml.append(v)
    if tem_shopee:
        titulo_shopee=st.text_input("Título Shopee")
        st.caption(f"{len(titulo_shopee)} caracteres · 1 título para os canais Shopee selecionados")
    if tem_tiktok:
        titulo_tiktok=st.text_input("Título TikTok Shop")
        st.caption(f"{len(titulo_tiktok)} caracteres · 1 título para TikTok Shop")

    descricao=st.text_area("Descrição — válida para o SKU",height=220)
    st.caption(f"{len(descricao)} caracteres")

    preco_premium=preco_classico=preco_shopee=preco_tiktok=0.0
    if tem_ml or tem_shopee or tem_tiktok:
        st.subheader("Preços por plataforma")
    if tem_ml:
        c1,c2=st.columns(2)
        preco_premium=c1.number_input("Preço Premium — Mercado Livre",0.0,step=0.01)
        preco_classico=c2.number_input("Preço Clássico — Mercado Livre",0.0,step=0.01)
    if tem_shopee and tem_tiktok:
        c1,c2=st.columns(2)
        preco_shopee=c1.number_input("Preço Shopee",0.0,step=0.01)
        preco_tiktok=c2.number_input("Preço TikTok Shop",0.0,step=0.01)
    elif tem_shopee:
        preco_shopee=st.number_input("Preço Shopee",0.0,step=0.01)
    elif tem_tiktok:
        preco_tiktok=st.number_input("Preço TikTok Shop",0.0,step=0.01)

    if st.button("CRIAR E ENVIAR PARA BASE",type="primary",use_container_width=True):
        erros=[]
        if not sku:erros.append("Informe o SKU.")
        if not canais:erros.append("Selecione pelo menos um canal de publicação.")
        if not descricao.strip():erros.append("Preencha a descrição.")
        if tem_ml and (not titulos_ml or any(not x.strip() for x in titulos_ml)):erros.append("Preencha todos os títulos do Mercado Livre.")
        if tem_ml and (preco_premium<=0 or preco_classico<=0):erros.append("Informe os preços Premium e Clássico do Mercado Livre.")
        if tem_shopee and preco_shopee<=0:erros.append("Informe o preço da Shopee.")
        if tem_tiktok and preco_tiktok<=0:erros.append("Informe o preço do TikTok Shop.")
        if tem_shopee and not titulo_shopee.strip():erros.append("Preencha o título da Shopee.")
        if tem_tiktok and not titulo_tiktok.strip():erros.append("Preencha o título do TikTok Shop.")
        if erros:
            for e in erros:st.error(e)
        else:
            criar_produto(sku,canais,len(titulos_ml),titulos_ml,titulo_shopee,titulo_tiktok,descricao,
                          preco_premium,preco_classico,preco_shopee,preco_tiktok,user,prioridade,str(prazo) if prazo else None)
            st.success("Produto e canais criados e enviados para BASE.")

else:
    q=st.text_input("Digite o SKU").strip().upper()
    if q:
        with con() as c:
            ans=c.execute("SELECT * FROM anuncios WHERE sku=%s ORDER BY numero",(q,)).fetchall()
            p=c.execute("SELECT * FROM produtos WHERE sku=%s",(q,)).fetchone()
            hist=c.execute("""SELECT h.data_hora,a.canal,h.etapa,h.acao,h.observacao FROM historico h
                JOIN anuncios a ON a.id=h.anuncio_id WHERE a.sku=%s ORDER BY h.id DESC""",(q,)).fetchall()
        if not ans:st.warning("SKU não encontrado.")
        for x in ans:
            with st.container(border=True):
                with con() as c:tits=titulos_anuncio(c,x["id"])
                st.write(f"**{x['sku']} · {x['canal'] or '—'}**")
                st.write(f"{x['prioridade']} · {x['etapa']} / {x['status']} · entrada {fmt(x['entrada_etapa_em'])}")
                resumo_anuncio(x,p,tits)
                if x.get("link_anuncio"):st.write(f"**Link publicado:** {x['link_anuncio']}")
                if x["status"]=="CORRIGIR":st.error(f"{x['correcao_destino']} precisa corrigir: {x['correcao_motivo']}")
        if hist:
            with st.expander("🕘 Linha do tempo completa",expanded=gest):
                st.dataframe([dict(x) for x in hist],use_container_width=True,hide_index=True)
